name: portfolio_web
description: "portfolio_web"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.9.1
  flutter_svg: ^2.2.1
  flutter_launcher_icons: ^0.14.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/res/profile.jpeg
    - assets/res/profile_image.png
    - assets/illustrations/developer_working.svg
    - assets/res/logo.svg
    - assets/icons/flutter.svg
    - assets/icons/dart.svg
    - assets/icons/android.svg
    - assets/icons/apple.svg
    - assets/icons/flutter_web.svg
    - assets/icons/node.svg
    - assets/icons/express.svg
    - assets/icons/api.svg
    - assets/icons/postman.svg
    - assets/icons/firebase.svg
    - assets/icons/sql.svg
    - assets/icons/AWS_S3.svg
    - assets/icons/jira.svg
    - assets/icons/clickUp.svg
    - assets/icons/windsurf.svg
    - assets/icons/responsive_design.svg
    - assets/icons/wordpress.svg
    - assets/icons/github.svg
    - assets/res/quran.png
    - assets/res/badr.jpeg
    - assets/res/habyn.jpeg
    - assets/res/TailorX.jpg
    - assets/res/gymApp.jpg
    - assets/res/scan_text_ai.jpg
    - assets/res/kanz_loan_app.jpeg
    - assets/res/Igloo.jpeg
    - assets/res/gem_store.jpeg


flutter_launcher_icons:
  web:
    generate: true
    image_path: assets/Favicon.svg